import type { Metadata } from "next";
import {Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { PrivacyAndCookies } from "@/ui-kit";

const raleway = Raleway({
  weight: ["500", "600"],
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${raleway.variable} antialiased font-raleway p-0  `}
      >
        <div className="fixed top-0 sm:top-10 left-0 right-0 m-0 z-50 flex justify-center">
          <Header />
        </div>
        <div id="main-content" className="flex align-middle justify-center max-w-360 sm:m-auto px-5 sm:px-25">
          {children}
        </div>
        <div className="mb-4 flex justify-center">
          <PrivacyAndCookies />
        </div>
      </body>
    </html>
  );
}
