import type { Metadata } from "next";
import {Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { PrivacyAndCookies } from "@/ui-kit";

const raleway = Raleway({
  weight: ["500", "600"],
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} antialiased font-raleway`}
      >
        <div className="fixed top-0 sm:top-10 left-0 right-0 z-50 flex justify-center">
          <Header />
        </div>
        {children}
        <div className="mb-4 left-0 right-0 flex justify-center">
          <PrivacyAndCookies />
        </div>
      </body>
    </html>
  );
}
